version: '3'
services:
  db:
    command: postgres -c max_connections=200
    image: postgres:10.2-alpine
    ports:
      - "5432:5432"

  parktool:
    image: nadberezny/parktool
    environment:
      - KAFKA_URL=kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    ports:
      - "9092:9092"
      - "2181:2181"
    expose:
      - "9092"
      - "2181"
