version: '3'
services:
  park_registry_db:
    command: postgres -c max_connections=200
    image: postgres:10.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=park_registry
    ports:
      - "5432:5432"

  parkcalculator:
    image: nadberezny/parkcalculator
    environment:
      - PARK_REGISTRY_JDBC_URL=jdbc:postgresql://park_registry_db/park_registry
      - PARK_REGISTRY_DB_USER=postgres
      - PARK_REGISTRY_DB_PASSWD=postgres
    ports:
      - "8090:8090"
    depends_on:
      - park_registry_db

  parktool:
    image: nadberezny/parktool
    environment:
      - KAFKA_URL=kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  parkregistry:
    image: nadberezny/parkregistry
    environment:
      - KAFKA_URL=kafka:9092
      - PARK_REGISTRY_JDBC_URL=jdbc:postgresql://park_registry_db/park_registry
      - PARK_REGISTRY_DB_USER=postgres
      - PARK_REGISTRY_DB_PASSWD=postgres
    depends_on:
      - kafka
      - park_registry_db

  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    ports:
      - "9092:9092"
      - "2181:2181"
    expose:
      - "9092"
      - "2181"
